# yml配置文件
spring:
  profiles:
    active: ali
  main:
    allow-circular-references: true
  datasource: #数据库连接信息
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动类名称
    url: jdbc:mysql://localhost:3306/tlias #数据库连接的url
    username: root #连接数据库的用户名
    password: 123456 #连接数据库的密码
  servlet:
    multipart:
      max-file-size: 10MB #配置单个文件上传大小限制
      max-request-size: 100MB #配置单个请求上传的大小
        
          

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mybatis的日志, 指定输出到控制台
    map-underscore-to-camel-case: true #开启mybatis的驼峰命名自动映射开关 a_column ------> aCloumn

#阿里云oss配置
aliyun:
  oss:  #引用ali配置文件
    endpoint: ${aliyun.oss.endpoint}
    accessKeyId: ${aliyun.oss.accessKeyId} 
    accessKeySecret: ${aliyun.oss.accessKeySecret}
    bucketName: ${aliyun.oss.bucketName}


#开启事务管理的日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug